In [218]:
import pandas as pd
import numpy as np

In [219]:
df = pd.read_csv('D:\degree\sem 6\dataset.csv')

In [220]:
df.columns

Index(['Destination Port', 'Flow Duration',
       'Total Fwd PacketsTotal Backward Packets', 'Unnamed: 3',
       'Total Length of Fwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std  ', 'Label'],
      dtype='object')

In [221]:
df.head()

Destination Port  Flow Duration  Total Fwd PacketsTotal Backward Packets  \
0             54865              3                                        2   
1             55054            109                                        1   
2             46236             34                                        1   
3             61374             61                                        1   
4             61326             68                                        1   

   Unnamed: 3  Total Length of Fwd Packets  Fwd Packet Length Max  \
0           0                           12                      0   
1           1                            6                      6   
2           1                            6                      6   
3           1                            6                      6   
4           1                            6                      6   

   Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std    \
0                      6                       6                        6   
1                      6                       6                        6   
2                      6                       6                        6   
3                      6                       6                        6   
4                      6                       6                        6   

    Label  
0    safe  
1  unsafe  
2  unsafe  
3  unsafe  
4    safe

In [222]:
df.isnull().sum()

Destination Port                           0
Flow Duration                              0
Total Fwd PacketsTotal Backward Packets    0
Unnamed: 3                                 0
Total Length of Fwd Packets                0
Fwd Packet Length Max                      0
Fwd Packet Length Min                      0
Fwd Packet Length Mean                     0
Fwd Packet Length Std                      0
Label                                      0
dtype: int64

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column                                   Non-Null Count  Dtype 
---  ------                                   --------------  ----- 
 0   Destination Port                         5 non-null      int64 
 1   Flow Duration                            5 non-null      int64 
 2   Total Fwd PacketsTotal Backward Packets  5 non-null      int64 
 3   Unnamed: 3                               5 non-null      int64 
 4   Total Length of Fwd Packets              5 non-null      int64 
 5   Fwd Packet Length Max                    5 non-null      int64 
 6   Fwd Packet Length Min                    5 non-null      int64 
 7   Fwd Packet Length Mean                   5 non-null      int64 
 8   Fwd Packet Length Std                    5 non-null      int64 
 9   Label                                    5 non-null      object
dtypes: int64(9), object(1)
memory usage: 532.0+ bytes


In [224]:
df

Destination Port  Flow Duration  Total Fwd PacketsTotal Backward Packets  \
0             54865              3                                        2   
1             55054            109                                        1   
2             46236             34                                        1   
3             61374             61                                        1   
4             61326             68                                        1   

   Unnamed: 3  Total Length of Fwd Packets  Fwd Packet Length Max  \
0           0                           12                      0   
1           1                            6                      6   
2           1                            6                      6   
3           1                            6                      6   
4           1                            6                      6   

   Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std    \
0                      6                       6                        6   
1                      6                       6                        6   
2                      6                       6                        6   
3                      6                       6                        6   
4                      6                       6                        6   

    Label  
0    safe  
1  unsafe  
2  unsafe  
3  unsafe  
4    safe

In [225]:
from sklearn.preprocessing import LabelEncoder

In [226]:
encoder = LabelEncoder()
df[' Label']=encoder.fit_transform(df['Label'])

In [227]:
df.head(10)


Destination Port  Flow Duration  Total Fwd PacketsTotal Backward Packets  \
0             54865              3                                        2   
1             55054            109                                        1   
2             46236             34                                        1   
3             61374             61                                        1   
4             61326             68                                        1   

   Unnamed: 3  Total Length of Fwd Packets  Fwd Packet Length Max  \
0           0                           12                      0   
1           1                            6                      6   
2           1                            6                      6   
3           1                            6                      6   
4           1                            6                      6   

   Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std    \
0                      6                       6                        6   
1                      6                       6                        6   
2                      6                       6                        6   
3                      6                       6                        6   
4                      6                       6                        6   

    Label   Label  
0    safe       0  
1  unsafe       1  
2  unsafe       1  
3  unsafe       1  
4    safe       0

In [228]:
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.model_selection import train_test_split

In [229]:
Target= ' Label'
X = df.loc[:,df.columns !=Target]
y = df.loc[:,Target]

In [230]:
#from sklearn.impute import SimpleImputer
#lower_bound=0
#upper_bound=100
#X_clipped = np.clip(X, lower_bound, upper_bound) 
#imputer = SimpleImputer(strategy='mean')
#X_imputed = imputer.fit_transform(X_clipped)

In [ ]:
import pandas as pd

# Assuming df is your DataFrame
print(df.columns)  # Check column names of df

# Verify column names specified in selected_features


# Check for typos and ensure column names match exactly
# Double-check the column names in the DataFrame
print(df.head())  # Print first few rows of the DataFrame

# Select the specified features from the DataFrame

from sklearn.impute import SimpleImputer
#lower_bound=0
#upper_bound=100
#X_clipped = np.clip(X, lower_bound, upper_bound) 
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform
# Print selected features
print(X.columns)
selector = SelectKBest(score_func=chi2, k=10)
selector.fit(X_imputed, y)
selected_features = selector.get_support(indices=True)
X_new = X_imputed[:, selected_features]
X_new_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.25)
selected_features=['Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std']
X = df[selected_features]
print(selected_features)

In [232]:
print(X)

   Destination Port  Flow Duration  Total Fwd PacketsTotal Backward Packets  \
0             54865              3                                        2   
1             55054            109                                        1   
2             46236             34                                        1   
3             61374             61                                        1   
4             61326             68                                        1   

   Unnamed: 3  Total Length of Fwd Packets  Fwd Packet Length Max  \
0           0                           12                      0   
1           1                            6                      6   
2           1                            6                      6   
3           1                            6                      6   
4           1                            6                      6   

   Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std    \
0                      6         

In [233]:
X_new

array([[5.4865e+04, 3.0000e+00, 2.0000e+00, 0.0000e+00, 1.2000e+01,
        0.0000e+00, 6.0000e+00, 6.0000e+00, 6.0000e+00],
       [5.5054e+04, 1.0900e+02, 1.0000e+00, 1.0000e+00, 6.0000e+00,
        6.0000e+00, 6.0000e+00, 6.0000e+00, 6.0000e+00],
       [4.6236e+04, 3.4000e+01, 1.0000e+00, 1.0000e+00, 6.0000e+00,
        6.0000e+00, 6.0000e+00, 6.0000e+00, 6.0000e+00],
       [6.1374e+04, 6.1000e+01, 1.0000e+00, 1.0000e+00, 6.0000e+00,
        6.0000e+00, 6.0000e+00, 6.0000e+00, 6.0000e+00],
       [6.1326e+04, 6.8000e+01, 1.0000e+00, 1.0000e+00, 6.0000e+00,
        6.0000e+00, 6.0000e+00, 6.0000e+00, 6.0000e+00]])

In [234]:
y.unique

<bound method Series.unique of 0    0
1    1
2    1
3    1
4    0
Name:  Label, dtype: int32>

In [235]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(X_new_train,y_train)

DecisionTreeClassifier()

In [236]:
y_pred=dtc.predict(X_test)

In [237]:
y_pred[:10]

array([1, 0])

In [238]:
y_test

4    0
2    1
Name:  Label, dtype: int32

In [239]:
y_test[:10]

4    0
2    1
Name:  Label, dtype: int32

In [240]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error( y_test,y_pred)

0.5

In [241]:
import joblib

# Assuming 'dtr' is your trained Decision Tree model

# Save the trained Decision Tree model
joblib.dump(dtc, 'decision_tree_model.pkl')


['decision_tree_model.pkl']

In [242]:
from sklearn.ensemble import RandomForestClassifier

In [243]:
rf_reg= RandomForestClassifier(n_estimators=500 )
rf_reg.fit(X_new_train,y_train)

RandomForestClassifier(n_estimators=500)

In [244]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the RandomForestClassifier with max_depth parameter
model = RandomForestClassifier(max_depth=10)  # Set max_depth to the desired value, e.g., 10

# Train the model on your training data
model.fit(X_new_train, y_train)


RandomForestClassifier(max_depth=10)

In [245]:
y_pred=rf_reg.predict(X_test)

In [246]:
y_pred

array([1, 1])

In [247]:
y_pred = pd.DataFrame(data=y_pred,columns=['pred'])
y_pred

pred
0     1
1     1

In [248]:
y_test

4    0
2    1
Name:  Label, dtype: int32

In [249]:
print(mean_squared_error(y_test,y_pred))

0.5


In [250]:
import joblib
joblib.dump(rf_reg, 'model.pkl')


['model.pkl']

In [251]:
pd.DataFrame(X_new_train)

0      1    2    3     4    5    6    7    8
0  61374.0   61.0  1.0  1.0   6.0  6.0  6.0  6.0  6.0
1  55054.0  109.0  1.0  1.0   6.0  6.0  6.0  6.0  6.0
2  54865.0    3.0  2.0  0.0  12.0  0.0  6.0  6.0  6.0

In [252]:
y_train

3    1
1    1
0    0
Name:  Label, dtype: int32

In [253]:
np.nan_to_num(X)

array([[54865, 3, 2, 0, 12, 0, 6, 6, 6, 'safe'],
       [55054, 109, 1, 1, 6, 6, 6, 6, 6, 'unsafe'],
       [46236, 34, 1, 1, 6, 6, 6, 6, 6, 'unsafe'],
       [61374, 61, 1, 1, 6, 6, 6, 6, 6, 'unsafe'],
       [61326, 68, 1, 1, 6, 6, 6, 6, 6, 'safe']], dtype=object)

In [254]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score

In [255]:
models={
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "Naive Bayes":GaussianNB(),
    "Logistic Regression":LogisticRegression()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_new_train,y_train) #train model

    #make prediction
    y_train_pred =model.predict(X_new_train)
    y_test_pred =model.predict(X_test)

    #Training set performance
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)


    #Test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Tranning Set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print("- F1 Score: {:.4f}".format(model_train_f1))  

    print("- Precision: {:.4f}".format(model_train_precision))
    print("- Recall: {:.4f}".format(model_train_recall))
    print("- Roc Auc Score: {:.4f}".format(model_train_rocauc_score))


    print('----------------------------------------------------------------')

    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(model_test_accuracy))
    print("- F1 Score: {:.4f}".format(model_test_f1))  

    print("- Precision: {:.4f}".format(model_test_precision))
    print("- Recall: {:.4f}".format(model_test_recall))
    print("- Roc Auc Score: {:.4f}".format(model_test_rocauc_score))

    print('='*35)
    print('\n')








Decision Tree
Model performance for Tranning Set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------------------------------------
Model performance for Test set
- Accuracy: 0.5000
- F1 Score: 0.3333
- Precision: 0.5000
- Recall: 1.0000
- Roc Auc Score: 0.5000


Random Forest
Model performance for Tranning Set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------------------------------------
Model performance for Test set
- Accuracy: 0.5000
- F1 Score: 0.3333
- Precision: 0.5000
- Recall: 1.0000
- Roc Auc Score: 0.5000


Naive Bayes
Model performance for Tranning Set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
----------------------------------------------------------------
Model performance for Test set
- Accuracy: 0.5000
- F1 Score: 0.3333
- Precision: 0.5000
- Recall: 

In [256]:
import pandas as pd
df = pd.read_csv('C:\\Users\\Bhushan\\Desktop\\botnet project\\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')
selected_features=['Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std']
X = df[selected_features]
print(selected_features)


['Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']


In [257]:
print(len(selected_features))

10
